[package]
name = "light-sol-program-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
light-sol-bankrun = { path = "../runtime" }
solana-sdk = "1.17"

[dev-dependencies]
spl-token = "3.5.0"
